apiVersion: apps/v1
kind: Deployment
metadata:
  name: tix-payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tix-payments
  template:
    metadata:
      labels:
        app: tix-payments
    spec:
      containers:
        - name: tix-payments
          image: vahramj/tix-payments
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: MONGODB_URI
              value: 'mongodb://tix-payments-mongo-srv:27017/payments'
            - name: STAN_CLUSTER_ID
              value: ticketing
            - name: STAN_URL
              value: 'http://nats-srv:4222'
            - name: STAN_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: tix-payments-srv
spec:
  selector:
    app: tix-payments
  ports:
    - name: tix-payments
      protocol: TCP
      port: 3000
      targetPort: 3000
